{
 "title": "Switch global view",
 "tags": [ "ruckus" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Device",
    "query": {
     "query": "label_values(up{job=~\"Switches|SWITCH|Router*\"},instance)"
    }
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "ifHCInOctets{job=~\"Router.*|Switches.*\",instance=\"$Device\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Switch Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance='$Device'}/100"
    }
   ]
  },
  {
   "title": "CPU level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "snAgentCpuUtilPercent{instance='$Device',snAgentCpuUtilCpuId=\"1\",snAgentCpuUtilInterval=\"1\",snAgentCpuUtilSlotNum=\"1\"} * 0.5",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "snAgentTemp2Value{instance='$Device'}/2",
     "legendFormat": "Temp ID {{snAgentTemp2SensorId}}"
    }
   ]
  },
  { "title": "Interfaces detail $interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "interface" },
  {
   "title": "Traffic ${interface}",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "repeat": "Interface",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "PortState",
     "decimals": 2,
     "disabledValue": "2",
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "ifOperStatus{instance='$Device',ifDescr='$interface'}",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "Port State",
     "units": "none",
     "valueHandler": "Disable Criteria"
    },
    {
     "aggregation": "Last",
     "alias": "PortSpeed",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "ifHighSpeed{instance='$Device',ifDescr='$interface'}",
     "group": { "alias": "", "name": "Values", "url": "" },
     "legendFormat": "Port Speed",
     "units": "Mbits",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "PortPower",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "snAgentPoePortConsumed{instance='$Device',ifDescr='$interface'}/1000",
     "group": { "alias": "", "name": "Values", "url": "" },
     "legendFormat": "Port Power",
     "units": "watt",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Port MTU",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "ifMtu{instance='$Device',ifDescr='$interface'}",
     "group": { "alias": "", "name": "Values", "url": "" },
     "legendFormat": "MTU",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Traffic ${interface}",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 9 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{instance='$Device',ifDescr='$interface'}[10m]) * 8",
     "legendFormat": "In"
    },
    {
     "expr": "rate(ifHCOutOctets{instance='$Device',ifDescr='$interface'}[10m]) * 8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Multicast ${interface}",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifHCInMulticastPkts{instance='$Device',ifDescr='$interface'}[10m])",
     "legendFormat": "In"
    },
    {
     "expr": "rate(ifHCOutMulticastPkts{instance='$Device',ifDescr='$interface'}[10m])",
     "legendFormat": "Out"
    }
   ]
  }
 ]
}