{
 "title": "Switch Interface Explorer",
 "tags": [ "ruckus" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Device",
    "query": {
     "query": "label_values(up{job=~\"Switches\"},instance)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "ifHCInOctets{job=~\"Switches.*\",instance=\"$Device\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Port Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sysUpTime{instance='$Device'}*10) - max(ifLastChange{instance='$Device',ifDescr='$Interface'}*10)",
     "legendFormat": "MTU"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{instance='$Device',ifDescr='$Interface'}",
     "legendFormat": "ON / OFF"
    }
   ]
  },
  {
   "title": "PoE Class",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snAgentPoePortClass{instance='$Device',ifDescr='$Interface'}",
     "legendFormat": "MTU"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifHighSpeed{instance='$Device',ifDescr='$Interface'}",
     "legendFormat": "MTU"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance='$Device',ifDescr='$Interface'}[10m]) * 8",
     "legendFormat": "In"
    },
    {
     "expr": "irate(ifHCOutOctets{instance='$Device',ifDescr='$Interface'}[10m]) * 8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "MTU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifMtu{instance='$Device',ifDescr='$Interface'}",
     "legendFormat": "MTU"
    }
   ]
  },
  {
   "title": "PoE Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snAgentPoePortConsumed{instance='$Device',ifDescr='$Interface'}/1000",
     "legendFormat": "MTU"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifInErrors{instance='$Device',ifDescr='$Interface'}[10m]) * 8",
     "legendFormat": "In"
    },
    {
     "expr": "irate(ifOutErrors{instance='$Device',ifDescr='$Interface'}[10m]) * 8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Multicast",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{instance='$Device',ifDescr='$Interface'}[10m])",
     "legendFormat": "In"
    },
    {
     "expr": "irate(ifHCOutMulticastPkts{instance='$Device',ifDescr='$Interface'}[10m])",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "ifHighSpeed{instance='$Device',ifDescr='$Interface'}",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Status over time",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ifOperStatus{instance='$Device',ifDescr='$Interface'}",
     "legendFormat": "Oper"
    },
    {
     "expr": "ifAdminStatus{instance='$Device',ifDescr='$Interface'}",
     "legendFormat": "Admin"
    }
   ]
  },
  {
   "title": "Broadcast",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInBroadcastcastPkts{instance='$Device',ifDescr='$Interface'}[10m])",
     "legendFormat": "In"
    },
    {
     "expr": "irate(ifHCOutBroadcastPkts{instance='$Device',ifDescr='$Interface'}[10m])",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Port UpTime",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ifMtu{instance='$Device',ifDescr='$Interface'}",
     "legendFormat": "MTU"
    }
   ]
  }
 ]
}