{
 "title": "Synology DashBoard",
 "description": "A Dashboard for Synology NAS based on SNMP and Prometheus",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_uname_info{job=~\"NAS\"},nodename)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{job=\"NAS\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"NAS\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"NAS\"} / (node_memory_MemTotal_bytes{job=\"NAS\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"NAS\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {job=\"NAS\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{job=\"NAS\"} / node_memory_SwapTotal_bytes{job=\"NAS\"})) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "raidStatus",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_md_disks{device=\"md0\"}"
    }
   ]
  },
  {
   "title": "TX",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{device=\"eth0\",job=\"NAS\"}"
    }
   ]
  },
  {
   "title": "RX",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_network_receive_packets_total{device=\"eth0\",job=\"NAS\"}"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/vg1000/lv\",fstype=\"ext4\",mountpoint=\"/volume1\"}"
    }
   ]
  },
  {
   "title": "temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"platform_a375_temp_0\",sensor=\"temp1\"}*1000"
    }
   ]
  },
  {
   "title": "Trafick of eth0 Interfaces",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 5 },
   "repeat": "Interface",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eth0\",job=\"NAS\"}[5m])",
     "legendFormat": "In"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eth0\",job=\"NAS\"}[5m])",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{job=\"NAS\",mode=\"system\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{job=\"NAS\",mode=\"user\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{job=\"NAS\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{job=\"NAS\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Total"
    }
   ]
  },
  {
   "title": "FS Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "node_filesystem_device_error{job=\"NAS\"}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"NAS\"}",
     "legendFormat": "Load"
    }
   ]
  }
 ]
}